#!/bin/sh

mkdir -p opk
cp ./ketm.elf opk/ketm.elf
cp ./ketm.png opk/icon.png
cp -r ./data opk/
cp ./old_README.txt opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=KETM
Comment=Kill everything that moves
Exec=ketm.elf
Icon=icon
Terminal=false
Type=Application
Categories=games;' > opk/default."$1".desktop

mksquashfs ./opk ketm_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
