#!/bin/sh

mkdir -p ipkg/home/retrofw/games/ketm
mkdir -p ipkg/home/retrofw/apps/gmenu2x/sections/emulators
cp -r data ipkg/home/retrofw/games/ketm/
cp ./ketm.elf ipkg/home/retrofw/games/ketm/ketm
cp ./ketm.png ipkg/home/retrofw/games/ketm/ketm.png

cd ipkg

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print 'Package: ketm
Version: 1.0
Description: Schmup game
Section: games
Priority: optional
Maintainer: gameblabla
Architecture: mipsel
Homepage: https://github.com/gameblabla/ketm
Depends:
Source: https://github.com/gameblabla/ketm' > control

print '2.0' > debian-binary

print 'title=Ketm
description=Schmup game
exec=/home/retrofw/games/ketm/ketm
clock=600' > home/retrofw/apps/gmenu2x/sections/emulators/ketm

tar -czvf control.tar.gz control --owner=0 --group=0
tar -czvf data.tar.gz home --owner=0 --group=0
ar rv ../ketm.ipk control.tar.gz data.tar.gz debian-binary

cd ..
rm -r ipkg
